routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin')
    ->middleware('auth')
    ->namespace('Admin')
    ->as('admin.')
    ->group(function ($router) {
        $router->get('/', function () { return view('admin.home'); });

        $router->get('terms', 'TermsController@edit');
        $router->put('terms', 'TermsController@update')->name('terms.store');

        $router->resource('categories', CategoryController::class);
        $router->resource('structures', StructureController::class);
        $router->resource('products', ProductController::class);
        $router->resource('products.pictures', ProductPictureController::class);
        $router->resource('orders', OrderController::class);
        $router->resource('orders.details', OrderDetailController::class);

        $router->get('users/{user}/password', 'UserController@showPassword');
        $router->put('users/{user}/password', 'UserController@changePassword')->name('users.password');
        $router->resource('users', UserController::class);

        $router->get('orders/{order}/pdf-export', 'OrderController@pdfExport');

        $router->resource('settings', SettingsController::class)->only('edit', 'update');
    });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/about-us', 'HomeController@about');
Route::get('/catalogs', 'HomeController@showCatalogs');
Route::get('/contact', 'HomeController@showContact');
Route::get('/terms', 'HomeController@showTerms');
Route::post('/contact', 'HomeController@sendContact')->name('contact.post');
Route::get('/order', 'HomeController@showOrder')->name('orders.create');
Route::post('/order', 'HomeController@saveOrder')->name('orders.store');
Route::get('/{slug}', 'CategoryController@show');
Route::get('/{categorySlug}/{productSlug}', 'ProductController@show');

app/Structure.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Nicolaslopezj\Searchable\SearchableTrait;

class Structure extends Model
{
    use SearchableTrait;

    protected $fillable = ['name', 'is_active'];

    protected $casts = ['is_active' => 'boolean'];

    protected $searchable = [
        'columns' => [
            'name' => 10
        ]
    ];
}

app/Http/Controllers/Admin/StructureController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Structure;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;

class StructureController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $structures = Structure::search(request('search'))
            ->orderBy(request('sort', 'id'), request('order', 'asc'))
            ->paginate(10);

        return view('admin.structures.index', compact('structures'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.structures.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Structure::create($this->makeValidation($request));

        return redirect()->route('admin.structures.index');
    }

    protected function makeValidation($request)
    {
        return $this->validate($request, [
            'name' => 'required|max:255',
            'is_active' => 'required'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Structure  $Structure
     * @return \Illuminate\Http\Response
     */
    public function show(Structure $structure)
    {
        return redirect()->route('admin.structures.edit', $structure->id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Structure  $Structure
     * @return \Illuminate\Http\Response
     */
    public function edit(Structure $structure)
    {
        return view('admin.structures.edit', compact('structure'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\AppStructure  $appStructure
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Structure $structure)
    {
        $structure->update($this->makeValidation($request));

        return redirect()->route('admin.structures.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\AppStructure  $appStructure
     * @return \Illuminate\Http\Response
     */
    public function destroy(Structure $structure)
    {
        //
    }
}

resources/views/admin/structures/create.blade.php
@extends('adminlte::page')

@section('content')
    @box
        @slot('buttons')
            <a href="{{ route('admin.structures.index') }}" class="btn btn-default">
                <i class="fa fa-backward"></i>
                Inapoi
            </a>
        @endslot

        {!! Form::open()->route('admin.structures.store') !!}
            {!! Form::text('name', 'Nume') !!}
            {!! Form::select('is_active', 'Nume', [0 => 'Nu', 1 => 'Da'], 1) !!}
            {!! Form::submit('Salveaza')->success() !!}
        {!! Form::close() !!}
    @endbox
@endsection

resources/views/admin/structures/edit.blade.php
@extends('adminlte::page')

@section('content')
    @box
        @slot('buttons')
            Editeaza culoare #{{ $structure->id }}
        @endslot

        {!! Form::open()->put()->route('admin.structures.update', [$structure->id])->fill($structure) !!}
            {!! Form::text('name', 'Nume') !!}
            {!! Form::select('is_active', 'Nume', [0 => 'Nu', 1 => 'Da']) !!}
            {!! Form::submit('Modifica') !!}
            {!! Form::anchor('Inapoi')->route('admin.structures.index') !!}

        {!! Form::close() !!}
    @endbox
@endsection

resources/views/admin/structures/index.blade.php
@extends('adminlte::page')

@section('content')
    @box
        @slot('buttons')
            <div class="col-md-8">
                @add(['route' => 'admin.structures.create', 'name' => 'categorie'])
                @endadd
            </div>

            <div class="col-md-4">
                @search(['route' => 'admin.structures.index'])
                @endsearch
            </div>
        @endslot

        @if ($structures->count())
            <table class="table table-bordered table-hover">
                @theader(['columns' => [
                    'id' => 'Id',
                    'name' => 'Nume',
                    'is_active' => 'E activ',
                    'created_at' => 'Creat la',
                    'updated_at' => 'Modificat la',
                    'none' => 'Actiuni'
                ]])
                @endtheader

                <tbody>
                    @foreach ($structures as $structure)
                        <tr>
                            <td>{{ $structure->id }}</td>
                            <td>{{ $structure->name }}</td>
                            <td>{{ $structure->is_active ? 'Da' : 'Nu' }}</td>
                            <td>{{ $structure->created_at->format('d.m.Y H:i:s') }}</td>
                            <td>{{ $structure->updated_at->format('d.m.Y H:i:s') }}</td>
                            <td>
                                <a href="{{ route('admin.structures.edit', $structure->id) }}" class="btn btn-xs">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            {{ $structures->links() }}
        @else
            Nu exista inregistrari
        @endif
    @endbox
@endsection

@section('js')
@endsection